main-settings:
  property-a: git value 1
  property-b: git value 2
  override-a: ${app.main-settings.override-a:not-overridden}
mongodb:
  url: mongodb://${${mongo.user}.user}:${${mongo.user}.pass}@127.0.0.1:27017/${mongo.dbname}/
